- pack/core_encounter.json
Fix numbering for Heart-Shaped Herb and The Vulture's Plan.
Remove the extra text on Charge.
> Fix in-set numbering

- pack/bkw.json
Noticed that Counterattack cost was incorrect. It's quite obvious when you see the image next to it with a big fat "1" on it :)
> fix cost of counterattack, it costs 1 not 2 resources

- packs.json
Scarlet Witch release date was missing, which I'm guessing is why Scarlet Witch decks can't be published on marvelcdb.
> Add scarlet witch release date

- pack/thor.json
The trait "Condition" was missing in the data for Enhanced Physique.
> Add the trait "Condition" to Enhanched Physique

- pack/gmw.json
- pack/msm.json
- pack/trors.json
- translations/de/pack/msm.json
- translations/es/pack/core.json
- translations/es/pack/msm.json
- translations/fr/pack/gmw.json
- translations/fr/pack/msm.json
- translations/fr/pack/stld.json
- translations/fr/pack/twc_encounter.json
- validate.py
When searching for, "k:Weapon" Hand Cannon should appear in the results but does not.
When I look at Hand Cannon on the website it *looks* correct at first.
This seems to be because of a missing period in the json 
`		"traits": "Tech. Weapon",`
it seems like all traits should end with a period based on how the rest of the data is formatted. This theory is supported by how Nova does not show up when searching for "k:Champion" and it has the same error.
I did a regexp-search and tried to find all cards with this problem and fix them.
I also added a check to validate.py to catch most of these errors in the future as well.
> Fix missing periods in traits lists that made cards not show up in searches.

- pack/trors.json
This should fix zzorba/marvelsdb#118.
According to Hall of Heroes, the TRotRS card doesn't have the avenger trait, while the card from the Captain America pack does.
I am not sure if the card should have a unique code/ID if they will be considered two different cards due to the trait difference.
> Add Avengers Tower Card to TRotRS Pack

- pack/hood_encounter.json
**Modulars updated:**
* Beasty Boys
* Brothers Grimm
**Also:** 
* Fixes issue with tag incorrectly closed on the The Hood villain text
* Fixes Hinder (per hero) definition to remove unnecessary spaces
> Update data for The Hood modular sets - Part 1

- pack/hood_encounter.json
Update missing data on the following modular sets:
* Crossfire's Crew
* Mister Hyde
* Ransacked Armory
* Sinister Syndicate
* State of Emergency
* Streets of Mayhem
* Wrecking Crew
> Update The Hood modular sets - Part 2

- pack/hood_encounter.json
**Note:** the back side of Formidable Foe has a scheme acceleration icon on it, but I believe the double side cards currently don't support defining it? (I've encountered a similar situation in Vision's permanent upgrade with different illustrators on each side, and I could only define the front one) /cc @Kamalisk
> Add missing data to Standard II and Expert II sets

- pack/gambit.json
- pack/rogue.json
- schema/card_schema.json
I noticed that the resources weren't being validated when I saw some as strings and some as numbers. I went ahead and added the 4 resources to the card_schema.json and fixed a few validation issues with Rogue and Gambit.
Added
* resource_energy
* resource_mental
* resource_physical
* resource_wild
I also noticed that some original Arkham properties were still in the card_schema.json file from a very old commit so I removed them to clean it up a bit. Please let me know if I should do that on a separate PR.
Removed
* enemy_damage
* enemy_evade
* enemy_fight
* enemy_horror
* skill_agility
* skill_combat
* skill_intellect
* skill_wild
* skill_willpower
> Add resources to card schema for better validation

- pack/mts_encounter.json
- pack/mut_gen_encounter.json
- translations/de/pack/mut_gen_encounter.json
- translations/es/pack/mut_gen.json
- translations/it/pack/mut_gen_encounter.json
- translations/ko/pack/mts_encounter.json
- validate.py
I found out that the encounter cards haven't been validated from the initial commit because of an extra `not`. Once I removed that and validated the encounter cards, I found several errors that I tried to fix.
The biggest issue is that not all Traits end in a period (.), although nearly every one does. I found a few that end in an exclamation point (!) and then the Sinister Six villains end in activation numbers (Activation Order 1, Activation Order 2, etc). I updated the validation script to allow for these situations by adding a regex to check for period, exclamation point, or numbers as the trailing character.
With Odin's Torment (21138), the back_text was invalid so I tried to fix it. It looks like maybe a few villain scheme cards might be backwards by using the back_text and text in …
> Turn on validation for encounter cards

- pack/core_encounter.json
- translations/de/pack/core_encounter.json
- translations/fr/pack/core_encounter.json
- translations/it/pack/twc_encounter.json
[Yon-Rogg 01177](https://marvelcdb.com/card/01177) has a typo in the attack text where the bold tag isn't closed so most of the text is bolded. I'm closing the bold tag in the English, French, and German packs.
I did a global search for non-closed b tags and found another example for [Day of Reckoning 07004](https://marvelcdb.com/card/07004) in the Italian pack so I fixed that too.
> Fix Yon-Rogg text by closing bold tag

- pack/mut_gen.json
- pack/mut_gen_encounter.json
The `attack_cost` and `threat_cost` values were missing from most of the allies in the Mutant Genesis packs.
I also
* fixed a typo with Magneto/Erik Lehnsherr 32172b
* fixed Robert Kelly 32066 to have dashes for the attack and threat values (null in the JSON)
* added some `text` fields to some of the campaign allies
> Add attack_cost and threat_cost to Mutant Genesis allies

- pack/trors.json
I've updated the The Rise of Red Skull (TRORS) pack to include missing cards. This should fix https://github.com/zzorba/marvelsdb/issues/177.
I've added (all of these are duplicate cards that were already in other packs):
* Lead from the Front (04018)
* The Power of Leadership (04019)
* Energy (04023)
* Genius (04024)
* Strength (04025)
* Combat Training (04041)
* Tac Team (04042)
* Heroic Intuition (04046)
* Interrogation Room (04048)
* Energy (04050)
* Genius (04051)
* Strength (04052)
I think the pack position numbers might have been typos on some of them when they were published. For example, both the existing Ready for Action (04017) and the new Lead from the Front (04018) have position 17. I think the Resource cards might also be a little off with their pack position numbers.
> Add missing TRORS cards

- translations/de/pack/spdr.json
The German translation for the Spider-Ham ally (31021) was mistakenly linked to the SP//DR ally (30021). This caused the SP//DR ally to have Spider-Ham text and it caused the Spider-Ham ally to only have English text since the German translation wasn't linked to the card.
Both should now be fixed. This also addresses issue https://github.com/zzorba/marvelsdb/issues/178.
https://de.marvelcdb.com/card/30021
https://de.marvelcdb.com/card/31021
> Fix the German version of 31021

- pack/sm_encounter.json
This fixes several issues related to the Sinister Motives encounter cards.
* `base_threat` and `threat` are required properties when importing to the marvelsdb repo and those were missing for several main_schemes.
* `base_threat` and `base_threat_fixed` were used incorrectly for a lot of the cards. `base_threat_fixed` should be a boolean value but a lot of times the `base_threat` value was used instead.
* `scheme_text` was often used when `text` should have been used so the card's text data was missing.
* I also fixed several typos and formatting issues for cards.
> Fix Sinister Motives encounter cards

- packs.json
- translations/fr/packs.json
- translations/it/packs.json
- translations/ko/packs.json
The Ant-Man pack is currently named Ant-man so this fixes the name.
For some reason the German translation already had the correct value but the other languages were still using Ant-man as the pack name.
> Rename Ant-man pack to Ant-Man

- pack/angel.json
Both Psylocke and Angel have the Soaring Hearts Team-Up card.
This PR marks the Angel card (https://marvelcdb.com/card/42021) as a duplicate of the Psylocke card (https://marvelcdb.com/card/41020).
> Mark Soaring Hearts as a duplicate

- pack/next_evol.json
The text on [Plasma Rifle](https://marvelcdb.com/card/40011) had `[physical]` instead of `[energy]` for the resource to spend.
This fixes https://github.com/zzorba/marvelsdb/issues/210.
> Fix the text on Plasma Rifle 40011

- pack/mts_encounter.json
- translations/es/pack/sm_encounter.json
- translations/fr/pack/sm_encounter.json
- translations/it/pack/sm_encounter.json
There were a few cards that used `[strength]` instead of `[physical]` and `[genius]` instead of `[mental]` for the resource types.
> Change [strength] to [physical] and [genius] to [mental] for resource types

- pack/mts.json
From `After you resolve Adam Warlock's "Battle Mage" ability, exhaust Warlock's Cape → ready Adam Warlock's`
to `After you resolve Adam Warlock's "Battle Mage" ability, exhaust Warlock's Cape → ready Adam Warlock.`
> Typo fix on Warlock Cape

- pack/hood_encounter.json
updated "When Defeated" to "When Revealed"
> Typo fix for Hood(I) and Hood(II)

- pack/angel.json
- pack/mut_gen.json
- pack/next_evol.json
- pack/storm.json
- pack/wolv.json
- pack/x23.json
When editing deck, cards duplicate shouldn't be displayed
> fix duplicates

- pack/core.json
This fix should avoid duplicating the trait "Hero for Hire"
> fix hero for hire trait inconsistency

- pack/cap.json
Wrong trait for [Captain America's Helmet](https://marvelcdb.com/card/03008)
This should fix https://github.com/zzorba/marvelsdb/issues/233
> [cap] fix-cap-helmet-trait

- pack/nova.json
Nova appears 2 times in the following request, unlikely other heroes
> [nova] add hidden field on alter-ego

- pack/core_encounter.json
[The Break-In! - 1B](https://marvelcdb.com/card/01097) shouldn't have a crisis icon
This should fix https://github.com/zzorba/marvelsdb/issues/232
> [core] fix rhino main crisis

- pack/core.json
currently when searching for cards with "(attack)" in text, some results are missing, for example [Powered Gauntlets](https://marvelcdb.com/card/01038)
This should fix the behaviour also for thwart labeled cards
some results are missing, for example [Powered Gauntlets](https://marvelcdb.com/card/01038)
> Fix labeled attack and thwart search

- pack/iceman.json
Looking for Trouble is displayed twice in the deckbuilding panel
[Looking for Trouble](https://marvelcdb.com/card/16043)
[Looking for Trouble](https://marvelcdb.com/card/46017)
> [Iceman] fix looking for trouble duplicate

- pack/mojo_encounter.json
Adds more detail to the Longshot ally from MojoMania.
For reference:
https://marvelcdb.com/card/39071
> [MojoMania] Add more detail to Longshot ally

- pack/nebu.json
Lethal Intent should cost "X", which is denoted by `-1`:
> - **cost** - Play cost of the card. Relevant for most cards. Possible values:
>   - -1: Shows up as X
>   - 0+: Shows up as the given integer
For reference:
https://marvelcdb.com/card/22010
> [Nebula] Lethal Intent should have -1 ("X") cost

- pack/storm.json
Hangar Bay should have a mental resource.
For reference:
https://marvelcdb.com/card/36035
> [Hangar Bay] Add mental resource to Hangar Bay

- pack/trors.json
the set position is not well displayed on expert campaign cards of trotrs:
> [trotrs] fix expert campaign set position

- pack/mts_encounter.json
should fix https://github.com/zzorba/marvelsdb/issues/254
fix several issues on card [All Hail King Loki - 1A](https://marvelcdb.com/card/21165)
Typo: this tage -> this stage
Typo: players loose the game -> players lose the game
Typo: infinity Gauntlet -> Infinity Gauntlet
Typo: standard -> Standard
Typo: War in asgard -> War in Asgard
fix use of bold and italic tags
move 1A content to the back of card (like [The Break-In! - 1A](https://marvelcdb.com/card/01097))
> [MTS] fix Loki main scheme

- pack/aoa.json
Magik's Soulsword had a trait typo of Armor instead of Weapon.
> Fix Magik's Soulsword trait

- pack/vision.json
All other Alter-Ego cards are marked as `"hidden": true`, except for Vision.
This commit fixes that discrepancy.
> [Vision] Mark Vision's Alter-Ego side as hidden

- pack/aoa_encounter.json
fix type on [The Apocalypse Solution](https://marvelcdb.com/card/45111)
> [AoA] fix type on Apocalypse Solution

- pack/deadpool.json
- pack/gmw.json
fix typo on cards:
[Thruster Boots](https://marvelcdb.com/card/16039)
[Deadpool's Katana](https://marvelcdb.com/card/44010)
> [GMW][Deadpool] fix weapon typo

- pack/magneto.json
Noticed this when adding support for Magneto's Hero Pack in DragnCards.
> Face the Past only has 1 copy in Magneto's Precon

- pack/scw.json
Someone reported this to me when using DragnCards.
> There is only 1 copy of Order and Chaos in Scarlet Witch's precon

- pack/sm_encounter.json
This corrects a typo in the card text of Advanced Glider:
> (Limit once per round~er~ per player).
> Fix typo in Advanced Glider ("rounder" to "round")

- pack/sm.json
fix [Public Outcry](https://marvelcdb.com/card/27174b) icon: hazard instead acceleration
> [Sinister Motives] fix public outcry hazard icon

- pack/sm_encounter.json
["Leave Us Alone!" - 1A](https://marvelcdb.com/card/27076a)
> [Sinister Motives] fix leave-us-alone b side missing stage

- pack/hood_encounter.json
[Formidable Foe](https://marvelcdb.com/card/24049)
use back_link method instead double_sided method to add the missing acceleration icon on the B side
> [Hood] fix formidable foe missing acceleration icon

- README.md
just a proposal to document recent changes concerning double sided cards treatment
- double_sided method
- back_link method
see https://github.com/zzorba/marvelsdb-json-data/issues/549#issuecomment-2495656950 and https://github.com/zzorba/marvelsdb-json-data/pull/547#issuecomment-2561322676	
this should fix https://github.com/zzorba/marvelsdb-json-data/issues/549
> improve documentation for double sided cards

- pack/x23.json
Currently X-23 endurance is a duplicate of another duplicate
In marvelsdb, this causes the script php bin/console app:import:std path-to-marvelsdb-json-data/ to fail
This set X-23 endurance as duplicate of the original
> fix: X23 endurance, avoid duplicate of duplicate

- pack/trors_encounter.json
Fix typo on name of the B side on [The Rise of Red Skull - 1B](https://marvelcdb.com/card/04128a)
> [TROTRS] fix typo on main scheme

- README.md
- schema/card_schema.json
"cost_per_hero" is already used marvelsdb-json-data, but need documentation.
marvelsdb does not use that field yet.
[Team Investigation](https://marvelcdb.com/card/40053)
[Break Time](https://marvelcdb.com/card/44046)
> Add "cost_per_hero" documentation

- pack/mts.json
- translations/ko/pack/mts.json
A few cards in Mad Titan's Shadow were missing the proper `[[trait]]` markup.
> Fix some traits lacking proper markup

- pack/aoa_encounter.json
The title of https://marvelcdb.com/card/45076 should be Dark Designs instead of Dark Design.
This fixes https://github.com/zzorba/marvelsdb/issues/308.
> Fix name of 45076 to Dark Designs

- pack/hood_encounter.json
- pack/spiderham_encounter.json
This fixes two cards (24042 and 30024) which had `this cards gains surge` instead of `this card gains surge` typos
This fixes https://github.com/zzorba/marvelsdb/issues/311
> Fix cards that have the "cards gains" typo

- pack/bp.json
- pack/bp_encounter.json
- pack/silk.json
- pack/silk_encounter.json
- packs.json
This adds the remaining Black Panther and Silk cards that weren't spoiled by the time the previous two PRs (https://github.com/zzorba/marvelsdb-json-data/pull/592 and https://github.com/zzorba/marvelsdb-json-data/pull/603) were merged.
This adds the following cards:
* 51031
* 51035
* 51040
* 52022
* 52028
* 52038
It also fixes some quantities that were not entirely known at the time the previous PRs were created.
> Add remaining Black Panther and Silk cards to complete the packs

- pack/mojo_encounter.json
- pack/mts_encounter.json
- pack/mut_gen.json
- pack/sm_encounter.json
Fix typo on 'Old Grugde'
https://hallofheroeslcg.com/wp-content/uploads/2022/03/d.jpg
Fixes zzorba/marvelsdb#322
Fix typo on 'Find the Prisoners'
https://hallofheroeslcg.com/wp-content/uploads/2024/08/32173a.jpg
Fixes zzorba/marvelsdb#321
Fix typo on 'Mana Drain'
https://hallofheroeslcg.com/wp-content/uploads/2022/11/39046.jpg
Fixes zzorba/marvelsdb#319
Fix typo on 'Master of Illusions'
https://hallofheroeslcg.com/wp-content/uploads/2021/08/l14.jpg
Fixes zzorba/marvelsdb#312
> Fix multiple typos

- pack/aoa.json
- pack/aoa_encounter.json
- pack/bp.json
- pack/hood_encounter.json
- pack/jubilee.json
- pack/mut_gen_encounter.json
- pack/sm_encounter.json
Changes:
- `Sidekick` quantity 3 > 1
- `Heart of the Panther` quantity 2 > 1
- `Unlikely Duo` quantity 1 > 2
- `Armored Unibike` quantity 1 > 2
- `Magistrate` quantity 3 > 2
- `Master of Magnetism` quantity 2 > 3
- `Wrapped in Metal` quantity 2 > 1
- `Symbiotic Monstrosity` quantity 2 > 1
- `Tech Gauntlets` quantity 1 > 2
- `Jetpack` quantity 2 > 1
Fixes zzorba/marvelsdb#310
Fixes zzorba/marvelsdb#323
> Fix multiple quantity errors
