zzorba/marvelsdb-json-data

- pack/core_encounter.json
I don't know how to add the images, but at least all the cards will be there ;-)
> Expert encounter set is missing

- translations/fr/pack/cap.json
- translations/fr/pack/cap_encounter.json
- translations/fr/pack/msm.json
- translations/fr/pack/msm_encounter.json
- translations/fr/pack/thor.json
- translations/fr/pack/thor_encounter.json
Translation FR Captain America.
Core set & other packs coming in a week or two, sorry for the delay.
> Pack Captain America/Miss Marvel/Thor FR

- pack/core_encounter.json
- pack/trors.json
- packs.json
Three random data fixes:
- fix rhino stage 3 text
- add cgdb_id to trors
- fix jessica drew set code (was hawkeye)
Thank you! 🤓
> Updates to Rhino text, TRORS cgdb id, and Jessica Drew set

- translations/fr/pack/bkw.json
- translations/fr/pack/cap.json
- translations/fr/pack/cap_encounter.json
- translations/fr/pack/core.json
- translations/fr/pack/drs.json
- translations/fr/pack/msm.json
- translations/fr/pack/thor.json
Hi ! 
I spotted and corrected some error in the french translation (mostly typos and lack of translation)
> Correct some typos mistakes in French translation hero cards

- pack/ant.json
Correct the cost on Wrist Gauntlets. Was "-" should be 1.
> Update cost on Wrist Gauntlets and resource on Hive Mind

- pack/bkw.json
There was an extra `d` in the word `card`.
> Update bwk.json to fix typo

- translations/fr/pack/hlk.json
Add French translation for "Drop Kick"
> fix missing Drop Kick french translation

- pack/cap.json
- pack/core_encounter.json
- pack/hlk_encounter.json
- pack/toafk_encounter.json
- pack/trors.json
- pack/wsp.json
Data Fixes for various older cards with missing or incorrect text:
MarvelsDB Issues #84, 79, 75, 74, 72, 71, 70
> Data Fixes

- pack/ant.json
- pack/cap.json
- pack/core.json
- pack/gam.json
- pack/hlk.json
- pack/qsv.json
- pack/scw.json
- pack/stld.json
- pack/thor.json
- pack/trors.json
- pack/twc_encounter.json
- pack/wsp.json
Resolves:
https://github.com/zzorba/marvelsdb/issues/101
https://github.com/zzorba/marvelsdb/issues/99
> Consistency Fixes + A Couple Typos

- translations/fr/pack/core_encounter.json
- translations/fr/pack/gmw.json
- translations/fr/pack/msm.json
- translations/fr/pack/scw.json
- translations/fr/pack/stld.json
- translations/fr/pack/trors.json
- translations/fr/pack/wsp.json
- translations/fr/packs.json
- translations/fr/sets.json
Here comes the french translation of the Star-lord pack
> Star-Lord French Translation 🥖

- pack/mts.json
- pack/mts_encounter.json
- sets.json
Based on comments in pull request #126
> MTS data missing and fixed

- pack/nebu.json
Nebula's alter-ego ability was wrong.
> Fix Nebula alter-ego ability

- translations/de/pack/msm.json
Fully translated Ms. Marvel Cards.
> Ms. Marvel (german translation)

- translations/de/pack/cap.json
Captain America Cards fully translated.
> Captain America (german translation)

- translations/de/pack/bkw.json
- translations/de/pack/core.json
- translations/de/pack/hlk.json
Fixed some typos, I found while deckbuilding.
> German Typos

- translations/de/pack/cap.json
- translations/de/pack/drs.json
- translations/de/pack/mts.json
- translations/de/pack/mts_encounter.json
- translations/de/pack/nebu.json
- translations/de/pack/thor.json
- translations/de/pack/trors_encounter.json
- translations/de/pack/vision.json
- translations/de/pack/vision_encounter.json
- translations/de/pack/vnm.json
- translations/de/pack/vnm_encounter.json
Germany (and Friends) are finally in line with the rest of the world!
> German Translation Phase 4

- translations/de/pack/vision_encounter.json
- translations/de/packs.json
- translations/de/sets.json
I added the missing translations for german, so now all up and including Mad Titan's Shadow should be included.
> Addition of missing german translations

- translations/de/pack/sm.json
> German Sinister Motives Translations

- translations/es/pack/hood_encounter.json
- translations/es/pack/nebu_encounter.json
- translations/es/pack/sm.json
- translations/es/pack/sm_encounter.json
- translations/es/packs.json
- translations/es/sets.json
> Sinister Motives Spanish translations (hero cards)

- pack/gmw.json
- pack/gmw_encounter.json
- pack/hood_encounter.json
- pack/mts_encounter.json
- pack/warm_encounter.json
- translations/de/pack/gmw.json
- translations/de/pack/gmw_encounter.json
- translations/de/pack/mts_encounter.json
- translations/de/pack/warm_encounter.json
- translations/es/pack/gmw.json
- translations/es/pack/gmw_encounter.json
- translations/es/pack/hood_encounter.json
- translations/es/pack/mts_encounter.json
- translations/es/pack/valk_encounter.json
- translations/es/pack/warm_encounter.json
- translations/fr/pack/mts.json
- translations/fr/pack/mts_encounter.json
- translations/it/pack/gmw.json
- translations/it/pack/gmw_encounter.json
- translations/it/pack/hood_encounter.json
- translations/it/pack/mts.json
- translations/it/pack/mts_encounter.json
- translations/it/pack/warm_encounter.json
- translations/ko/pack/gmw.json
- translations/ko/pack/gmw_encounter.json
- translations/ko/pack/mts_encounter.json
- translations/ko/pack/warm_encounter.json
`[per_player]` is not correctly converted to the expected icon:
Instead of the correct one, `[per_hero]`:
> Fixes invalid use of `[per_player]` instead of `[per_hero]`

- pack/sm_encounter.json
updating the modular encounters city in chaos, down to earth, goblin gear, guerrilla tactics and osborn tech.
I updated text, attack_text, scheme_text, boost_text, and back_text
> update mods encounter texts 1/2

- pack/sm_encounter.json
updated modular scheme whispers of paranoia, symbiotic strength, sinister assault, personal nightmare.
updated text, attack_text, boost_text, scheme_text
> updates mod encounters text 2/2

- pack/sm_encounter.json
For the encounters Venom, Mysterio & Sandman, I updated text, attack_text, scheme_text and boost_text
> update text for Venom, Mysterio & Sandman

- translations/es/pack/sm.json
> Small typos on Sinister Motives

- pack/nova.json
Adding "IsUnique" Parameter to Moon Girl
> Adding 'IsUnique" to Moon Girl Ally

- pack/core.json
> Add Clint Barton subname to core set Hawkeye ally

- translations/fr/pack/core.json
Adding subname + fixing traits
> [FR] Adding Hawkeye' subname

- translations/fr/pack/vnm.json
> [FR] Star-Lord - Moving attack text

- translations/fr/pack/wsp.json
- Wasp (Giant) : moving "Scheme_text" and "Attack_text" to "Text"
- Changing traits
> [FR] Minor changes

- translations/fr/packs.json
> [FR] Adding SP//dr and Spider-Ham

- translations/fr/sets.json
> [FR] [Sets] Adding Spider-Ham and SP/dr sets

- translations/fr/pack/spiderham.json
> [FR] [Spider-Ham] Creating file

- translations/fr/pack/spiderham_encounter.json
> [FR] [Spider-Ham Encounter] Creating file

- translations/fr/pack/spdr.json
> [FR] [SP//dr] Creating file

- translations/fr/pack/spdr_encounter.json
> [FR] [SP//dr encounter] Creating file

- translations/fr/pack/spdr.json
1/ Fixing card number of Spider-Ham
2/ Fixing text mistake for card 31029
> [FR] [SP//dr] Fixing minor mistakes

- translations/fr/pack/thor.json
> [FR] [Thor] [Card 6019] Fixing Trait

- translations/fr/pack/qsv.json
Fixing word "Tenance" to "Tenace"
> [FR] [Quicksilver] [Card 14029] Fixing minor fault

- translations/fr/pack/thor.json
Changing traits "Ataque" to "Attaque"
> [FR] [Thor] [Card 06005] Fixing traits

- translations/fr/pack/twc_encounter.json
Adding missing traits "Armure"
> [FR] [W. Crew] [Card 07409] Adding missing trait

- translations/fr/pack/gam_encounter.json
Changing trait "Elite" to "Élite"
> [FR] [Gamora] [Card 18026] Fixing Trait

- translations/fr/pack/cap.json
Adding missing"." in attack text
> [FR] [Cap. Am.] [Card 03014] Fixing text

- translations/fr/pack/nova.json
> [FR] [Nova] [Card 28026] Adding missing CR

- translations/fr/pack/sm.json
Changing "gange" to "gagne" in text
> [FR] [Sin. Mot.] [Card 27191] Fixing text

- translations/fr/pack/spdr.json
Addinf missing "/" in "SP//dr" in text
> [FR] [SPdr] [Card 31013] Fixing text

- translations/fr/packs.json
Adding packs Mutant Genesis, Cyclpos and Phoenix
> [FR] [MG/Cy/Ph] Adding packs

- translations/fr/sets.json
Adding Mutant Genesis, Cyclops and Phoenix sets, and missing SM sets
> [FR] [SM/MG/Cy/Ph] Adding sets

- translations/fr/pack/cyclops.json
> [FR] [Cyclops] Creating hero file

- translations/fr/pack/cyclops_encounter.json
> [FR] [Cyclops] Creating encounter file

- translations/fr/pack/mut_gen.json
> [FR] [MG] Creating hero file

- translations/fr/pack/mut_gen_encounter.json
> [FR] [MG] Creating encounter file

- translations/fr/pack/phoenix.json
> [FR] [Phoenix] Creating hero file

- translations/fr/pack/phoenix_encounter.json
> [FR] [Phoenix] Creating encounter file

- translations/fr/pack/wsp.json
> [FR] [Wasp] [Card 33] Fixing word

- translations/fr/pack/nova.json
> [FR] [Nova] [Card 27] Fixing text

- translations/fr/pack/sm_encounter.json
Adding missing \" in flavors text
> [FR] [SM_encounter] Fixing flavors

- translations/fr/pack/sm.json
> [FR] [SM] [Card 27017] Fixing boost

- pack/core.json
> Fix Luke Cage's missing quote

- translations/fr/packs.json
Adding Wolverine/Storm/Mojo packs
> [FR] [Pack] Adding Wolverine/Storm/Mojo

- translations/fr/sets.json
Adding Wolverine/Storm/Mojo sets
> [FR] [Set] Adding Wolverine/Storm/Mojo

- translations/fr/pack/mojo_encounter.json
> [FR] [Mojo] Creating encounter file

- translations/fr/pack/storm.json
> [FR] [Storm] Creating hero file

- translations/fr/pack/storm_encounter.json
> [FR] [Storm] Creating encounter file

- translations/fr/pack/wolv.json
> [FR] [Wolv] Creating hero file

- translations/fr/pack/wolv_encounter.json
> [FR] [Wolv] Creating encounter file

- translations/fr/pack/trors.json
Deleting the excess '.' in flavor
> [FR] [TRORS] [Card 11] Fixing flavor

- translations/fr/types.json
Fixing word "Traitrîse" to "Traîtrise"
> [FR] [Types] Fixing word

- translations/fr/pack/ron_encounter.json
> [FR] [Ronan] [005] Fixing word

- translations/fr/pack/stld.json
1/ For Yondu (card #13), fixing text and adding flavor. 2/ Other minor changes (flavor (#12) and trait (#17)),
> [FR] [Sr-Ld] [Card 13] Fixing card

- translations/fr/pack/trors.json
> [FR] [TRORS] Minor changes

- translations/fr/pack/core.json
Fixing name (01053) and text (01064)
> [FR] [Core] Minor Fixes

- translations/fr/pack/cyclops.json
> [FR] [Cyclops] [33033] Fixing Name

- pack/cyclops.json
See comment in https://marvelcdb.com/card/33009 for context
> Fixing name of Ricochet Beam

- translations/fr/packs.json
> [FR] [Packs] Adding Gambit and Rogue

- translations/fr/sets.json
> [FR] [Sets] Adding Gambit and Rogue

- translations/fr/pack/gambit.json
> [FR] [Gambit] Creating hero file

- translations/fr/pack/gambit_encounter.json
> [FR] [Gambit_Enc.] Creating hero file

- translations/fr/pack/rogue.json
> [FR] [Rogue] Creating hero file

- translations/fr/pack/sm.json
Fixing keyword [boost] in Venom text
> [FR] [SM] [Card 190] Fixing keyword

- translations/fr/pack/rogue_encounter.json
> [FR] [Rogue] Creating encounter file

- pack/mut_gen.json
> Update mut_gen.json - typo fix

- pack/cyclops.json
- pack/cyclops_encounter.json
- translations/es/pack/cyclops.json
This includes the following fixes to the Cyclops pack:
* Add `attack_cost` and `thwart_cost` to the allies
* Fix a few typos
* Add `text`, `attack_text`, `boost_text`, and `set_position` to nemesis set
> Update the Cyclops pack with various fixes

- pack/storm.json
Update the Storm pack with various fixes
* Add `attack_cost` and `thwart_cost` to allies
* Change hyphen `-` to em dash `—` for Storm's identity cards
* A few other typos/styling fixes
> Update Storm pack with various fixes

- translations/fr/pack/hlk.json
Minor fixes for card 10 (fixing word, adding flavor) and other minor fixes (cards 12 and 13)
> [FR] [Hulk] [Card 10] Minor fixes

- translations/fr/pack/mojo_encounter.json
Fixing boost text for cards #005 et #006
> [FR] [Mojo] Fixing boost text

- translations/fr/pack/rogue.json
> [FR] [Rogue] [Card 12] Fix Subname

- pack/wolv.json
fix consequential values on allies:
- sunfire
- psylocke
- jubilee
- longshot
> [Wolv] fix consequential values

- translations/fr/pack/gambit.json
Adding unuseless space in card #1a in order to try a re-commit because french translation not appears for Gambit
> [FR] [Gambit] Adding space

- translations/fr/pack/sm_encounter.json
Adding missing word in card #27123
> [FR] [SM_Enc] Adding missing word

- translations/fr/packs.json
> [FR] [NeXt E.] Adding pack

- translations/fr/types.json
> [FR] [NeXt E.] Adding type

- translations/fr/sets.json
Adding NeXt Evolution
=> Draft because waiting for the code for "Insurrection de Mutants" set
> [FR] [NeXt E.] Adding sets

- translations/fr/pack/next_evol.json
Adding NeXt Evolution
=> Draft because waiting for final tag for some text (text, health_text, scheme_text, attack_text, ...)
> [FR] [NeXt E.] Creating hero file

- translations/fr/pack/next_evol_encounter.json
Adding NeXt Evolution
=> Draft because waiting for final tag for some text (text, health_text, scheme_text, attack_text, ...)
> [FR] [NeXt E.] Creating encounter file

- pack/next_evol.json
this fix a typo, on the card E.V.A
https://marvelcdb.com/card/40021
> [next evol] fix eva typo

- translations/fr/packs.json
> [FR] [Packs] Adding Psylocke and Angel

- translations/fr/sets.json
> [FR] [Sets] Adding Psylocke and Angel

- translations/fr/pack/psylocke.json
> [FR] [Psylocke] Creating hero file

- translations/fr/pack/angel.json
> [FR] [Angel] Creating hero file

- translations/fr/pack/angel_encounter.json
> [FR] [Angel] Creating encounter file

- pack/drs.json
Adding isUnique property to card 26 (Sorcerer Supreme)
> [DRS] Adding isUnique (Card 26)

- translations/fr/pack/core.json
side a : translating "draw" text
side b : fixing text error
> [FR] [Core Set] [Card #01010] Fixing texts

- translations/fr/factions.json
[FR] [Faction] Adding Pool faction
> [FR] [Faction] Adding Pool faction

- translations/fr/packs.json
[FR] [Packs] Adding X-23 and Deadpool
> [FR] [Packs] Adding X-23 and Deadpool

- translations/fr/sets.json
[FR] [Sets] Adding X-23 and Deadpool
> [FR] [Sets] Adding X-23 and Deadpool

- translations/fr/pack/deadpool.json
[FR] [Deadpool] Creating hero file
> [FR] [Deadpool] Creating hero file

- translations/fr/pack/x23.json
[FR] [X-23] Creating hero file
> [FR] [X-23] Creating hero file

- pack/stld.json
fix [Cosmo](https://marvelcdb.com/card/17020) text
> [Stld] fix cosmo typo

- pack/storm.json
energy resource missing on ["To Me, My X-Men!"](https://marvelcdb.com/card/36020)
> [Storm] fix: to me my x-men resource

- pack/gam.json
https://marvelcdb.com/card/18002
> [Gamora] fix nebula ally text

- pack/x23.json
Text typo in [Shatterstar](https://marvelcdb.com/card/43015)
This should fix https://github.com/zzorba/marvelsdb/issues/234
> [X23] fix shatterstar text typo

- translations/fr/pack/qsv.json
Fixing text for cards #12 et #31
> [FR] [QSV] Fixing texts

- translations/fr/pack/qsv_encounter.json
> [FR] [QSV_Enc] [Card #26] Fixing text

- translations/fr/packs.json
> [FR] [Packs] Adding aoa

- translations/fr/sets.json
> [FR] [Sets] Adding aoa sets

- translations/fr/pack/aoa.json
> [FR] [AOA] Creating hero file

- translations/fr/pack/aoa_encounter.json
> [FR] [AOA] Creating encounter file

- translations/fr/packs.json
> [FR] [Packs] Adding Iceman

- translations/fr/sets.json
> [FR] [Sets] Adding Iceman

- translations/fr/pack/iceman.json
> [FR] [Iceman] Creating hero file

- translations/fr/pack/iceman_encounter.json
> [FR] [Iceman] Creating encounter file

- translations/fr/pack/x23.json
> [FR] [X23] [Card #18] Fix title

- translations/fr/pack/scw.json
> [FR] [Scarlet Witch] [Card 012] Fixing words

- pack/vnm.json
- translations/ko/pack/vnm.json
[Spider-Sense](https://marvelcdb.com/card/20009)
> [Venom] fix spider sense typo

- pack/gambit_encounter.json
- translations/es/pack/ant.json
- translations/es/pack/cap.json
- translations/es/pack/cyclops.json
- translations/es/pack/drs.json
- translations/es/pack/gambit_encounter.json
- translations/es/pack/hlk.json
- translations/es/pack/iceman.json
- translations/es/pack/ironheart_encounter.json
- translations/es/pack/jubilee.json
- translations/es/pack/msm.json
- translations/es/pack/mut_gen.json
- translations/es/pack/nova_encounter.json
- translations/es/pack/sm.json
- translations/es/pack/sm_encounter.json
- translations/es/pack/spiderham.json
- translations/es/pack/storm.json
- translations/es/pack/thor_encounter.json
- translations/es/pack/vision.json
I'm doing this Merge because the last merge not apear in the Spanish web and take the opportunity to solve a extra tab in a line and put the flavour text in Spanish. The last merge in this repository and the last merge in the other repository (marvelsdb)  not appear in the Spanish web @Kamalisk
> [ES] Correct text in translation and put flavor text in Iceman and Jubilee

- pack/mut_gen.json
[Phased and Confused](https://marvelcdb.com/card/32036)
> [Mut Gen] fix phased and confused typo

- translations/fr/sets.json
> [FR] [Sets] Adding Jubilee's sets

- translations/fr/pack/jubilee.json
> [FR] [Jubilee] Creating hero file

- translations/fr/pack/angel.json
> [FR] [Angel] [Card #30] Fixing title

- pack/deadpool_encounter.json
This should fix https://github.com/zzorba/marvelsdb/issues/247
> [Deadpool] fix typo anti regeneration ray

- pack/nebu.json
This should fix https://github.com/zzorba/marvelsdb/issues/248
> [Nebula] fix typo Evasive Maneuvering

- translations/fr/pack/phoenix.json
> [FR] [Phenix] [Card #34022] Fixing word

- pack/ncrawler_encounter.json
- translations/es/pack/cyclops.json
- translations/es/pack/jubilee_encounter.json
- translations/es/pack/mut_gen_encounter.json
- translations/es/pack/ncrawler.json
- translations/es/pack/ncrawler_encounter.json
- translations/es/pack/spdr.json
- translations/es/pack/trors_encounter.json
- translations/es/packs.json
- translations/es/sets.json
Nightcrawler in Spanish and correct a missing trait in Tweedledope
> [ES] Nightcrawler in Spanish

- pack/mojo_encounter.json
add +1 ATK and +1SCH on [Surge of Aggression](https://marvelcdb.com/card/39006)
replace [consequential] by [cost] on [The Mojo Files](https://marvelcdb.com/card/39047)
> [mojo] minor fix

- pack/aoa_encounter.json
typo:
[The Shadow King](https://marvelcdb.com/card/45180a)
add missing text:
[Abyss](https://marvelcdb.com/card/45181a)
[Mikhail Rasputin](https://marvelcdb.com/card/45183a)
> [AoA] fix overseer text

- translations/fr/pack/bkw.json
- translations/fr/pack/msm.json
- translations/fr/pack/mut_gen_encounter.json
- translations/fr/pack/ncrawler.json
- translations/fr/pack/ncrawler_encounter.json
- translations/fr/pack/next_evol.json
- translations/fr/pack/sm.json
- translations/fr/packs.json
- translations/fr/sets.json
> [FR] Fixing Texts and adding Nightcrawler

- pack/mts_encounter.json
[Avengers Tower](https://marvelcdb.com/card/21100)
> [MTS] fix avengers tower missing trait, double side display, and typo

- pack/gmw_encounter.json
- pack/mojo_encounter.json
- pack/mts_encounter.json
- pack/mut_gen_encounter.json
- pack/next_evol_encounter.json
- pack/sm_encounter.json
- pack/x23_encounter.json
Probably needs some checking if i didnt make any mistakes myself.
Maybe worth it to set up a spell checker for some fields like the text.
> Fix: Typos

- pack/valk_encounter.json
[Beguiled](https://marvelcdb.com/card/25031)
> [Valk] fix Beguiled trait enthralled

- translations/es/pack/magneto.json
- translations/es/pack/magneto_encounter.json
- translations/es/pack/mut_gen.json
- translations/es/packs.json
- translations/es/sets.json
- translations/es/subtypes.json
Magneto in Spanish and resolve a little thing in Mutant genesis
> [ES] Magneto in Spanish

- pack/gam.json
fix https://github.com/zzorba/marvelsdb/issues/276
fix https://github.com/zzorba/marvelsdb/issues/275
[Gamora](https://marvelcdb.com/card/18001a)
> [Gamora] fix hero and alter-ego typo

- pack/twc_encounter.json
[Breakout - 1A](https://marvelcdb.com/card/07001a)
fix https://github.com/zzorba/marvelsdb/issues/288
> [Wrecking Crew] Fix Wrecker typo

- pack/toafk_encounter.json
[The Master of Time - 2A](https://marvelcdb.com/card/11008a)
> [Kang] fix master of time base_threat

- pack/aoa_encounter.json
[Police State](https://marvelcdb.com/card/45138)
> [AoA] fix police state base_threat

- pack/mts_encounter.json
- pack/next_evol_encounter.json
[Odin](https://marvelcdb.com/card/21139a)
[Morlock](https://marvelcdb.com/card/40079)
> Fix missing attack cost and odin typo

- pack/deadpool.json
- translations/es/pack/angel.json
- translations/es/pack/ant.json
- translations/es/pack/aos.json
- translations/es/pack/aos_encounter.json
- translations/es/pack/cap.json
- translations/es/pack/mojo_encounter.json
- translations/es/pack/mut_gen_encounter.json
- translations/es/pack/sm.json
- translations/es/pack/storm.json
- translations/es/sets.json
- translations/es/types.json
See the changes in the set.json in english and change the set.json in the translate zone to match the changes
> [ES] Agents of S.H.I.E.L.D. encounters in Spanish

- translations/fr/pack/mut_gen.json
- translations/fr/pack/sm.json
- translations/fr/pack/warm.json
> [FR] Fix inflige typo

- translations/fr/pack/core_encounter.json
- translations/fr/pack/mts_encounter.json
- translations/fr/pack/trors.json
Fixes a couple of incorrect spellings of "stage", "resource" as they should be "stade", "ressource".
> [FR] Fix stade, ressource typos

- pack/mts.json
fix https://github.com/zzorba/marvelsdb/issues/301
[Monica Rambeau](https://marvelcdb.com/card/21001a)
> [MTS] fix Monica Rambeau ability typo

- pack/mut_gen.json
- translations/de/pack/mut_gen.json
- translations/es/pack/mut_gen.json
- translations/es/pack/mut_gen_encounter.json
- translations/fr/pack/mut_gen.json
- translations/fr/pack/mut_gen_encounter.json
- translations/it/pack/mut_gen.json
> Fix spelling of Kitty Pryde (not "Pride")

- pack/gambit.json
- translations/it/pack/gambit.json
> Fix capitalisation of Remy LeBeau (not "Lebeau")

- packs.json
- translations/de/packs.json
- translations/ko/packs.json
Box for reference:
and listing on [Fantasy Flight Games](https://www.fantasyflightgames.com/en/products/marvel-champions-the-card-game/):
> Fix name of The Galaxy's Most Wanted (added "The")

- pack/twc_encounter.json
This fixes https://github.com/zzorba/marvelsdb-json-data/issues/624
> Fix quantity of Energy Projects (07027)
